### ISSUE TITLE
Mailman 3 / Postorius / HyperKitty ?

### ISSUE THREAD

**Issue by pjz** [debops/ansible-mailman#1]
Any chance of an update to mailman 3 / Postorius / HyperKitty (installable via pip, if not yet via apt) ?

**Comment by drybjed** [comment]
Regarding Mailman 3: according to [this message](https://lists.debian.org/debian-devel/2014/05/msg00502.html) Mailman Team in Debian does not consider clean upgrade path from Mailman 2 to Mailman 3 and advises using a separate package. That would probably call for a separate Ansible role to handle the new version.

I'm not too keen on any other package managers than APT, and having a packaged MM3 in at least a `.deb` package, even in third-party repository, would be preferable for me.

As for the MM3 + Postorius + HyperKitty bundle, according to [these installation instructions](https://mailman-bundler.readthedocs.org/en/latest/) installing them seems to be more involved than previous version, and requires more software, like uwsgi which most likely should be handled by separate Ansible roles. Requirements should be handled first.

**Comment by drybjed** [comment]
The Mailman3 did not made it to Debian Stretch. I'm closing this issue for now due to inactivity. Mailman3 support might be added later in a new role.
